spring:
  data:
    rest:
      base-path: /api
  profiles:
    active: production
    
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
              
  datasource:
    url: jdbc:h2:mem:nextstep;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    driverClassName: org.h2.Driver
    username: sa
    password: nextstep
    
  jpa:
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
    database-platform: org.hibernate.dialect.H2Dialect    
    
security:
  oauth2:
    sso:
      login-path: /api/login

logging:
  level:
    org.springframework.security: DEBUG
    
github:
  client:
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user
    preferTokenInfo: false    
