server:
  port: 8080
  
spring:
  profiles:
    active: production
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  data:
    rest:
      base-path: /api
      
  datasource:
    url: jdbc:h2:mem:trello;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    driverClassName: org.h2.Driver
    username: sa
    password: nextstep
    
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect    

  resources:
    chain:
      enabled: true

#security:
#  oauth2:
##    sso:
##      login-path: /login


