spring:
  data:
    rest:
      base-path: /api
  profiles:
    active: production
    
  datasource:
    url: jdbc:h2:mem:nextstep;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    driverClassName: org.h2.Driver
    username: sa
    password: nextstep
    
security:
  oauth2:
    sso:
      login-path: /api/login