github:
  client:
    clientId: f0ace1ad945721e2c6e2
    clientSecret: 89b8cd1725cb96139697adc95d438d2f4cc70e26

#spring:
#  datasource:
#    url: jdbc:mysql://125.209.200.185:3306/nextstep?useUnicode=true&charsetEncoding=utf-8
#    username: nextstep
#    password: nextstep567