spring:
  data:
    rest:
      base-path: /api
  profiles:
    active: production

security:
  oauth2:
    sso:
      login-path: /api/login

#logging:
#  level:
#    org.springframework.security: DEBUG
